FROM nvidia/cuda:12.6.0-cudnn-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install -y python3.9 python3.9-dev python3-pip python3.9-distutils \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3.9 20 \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 20

WORKDIR /gen_attack

COPY . ./

RUN apt update \
    && apt install -y curl

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH /root/.local/bin:$PATH

RUN poetry config virtualenvs.create false \
    && poetry install
